about/urls.py
from django.urls import path

import about.views as views

urlpatterns = [path("about/", views.description)]

catalog/urls.py
from django.urls import path, re_path

import catalog.views as views

urlpatterns = [
    path("catalog/", views.item_list, name="catalog"),
    re_path(r"^catalog/(?P<num>[1-9]\d*)/$", views.item_details, name="catalog_item"),
]

feedback/urls.py
from django.urls import path

import feedback.views as views

urlpatterns = [path("feedback/", views.get_feedback, name="feedback")]

users/urls.py
from django.contrib.auth.views import *
from django.urls import path, re_path

from .views import profile, registration, user_details, users_list

urlpatterns = [
    path("login/", LoginView.as_view(template_name="auth/login.html")),
    path("logout/", LoginView.as_view(template_name="auth/logout.html")),
    path("registration/", registration),
    path(
        "password_change/", LoginView.as_view(template_name="auth/password_change.html")
    ),
    path(
        "password_change/done/",
        LoginView.as_view(template_name="auth/password_change_done.html"),
    ),
    path(
        "password_reset/", LoginView.as_view(template_name="auth/password_reset.html")
    ),
    path(
        "password_reset/done/",
        LoginView.as_view(template_name="auth/password_reset_done.html"),
    ),
    path(
        "reset/<uidb64>/<token>/",
        LoginView.as_view(template_name="auth/password_reset_confirm.html"),
    ),
    path(
        "reset/done/",
        LoginView.as_view(template_name="auth/password_reset_complete.html"),
    ),
    path("users/", users_list, name="users_list"),
    re_path(r"^users/(?P<num>[1-9]\d*)/$", user_details, name="user_details"),
    path("profile/", profile, name="change_password"),
]

about/models.py
# from django.db import models

# Create your models here.

catalog/models.py
from django.db import models
from django.utils.safestring import mark_safe
from PIL import Image
from sorl.thumbnail import get_thumbnail

from core.models import AbstractModelForCatalog

from .validators import (in_value_validator, num_compare_validator,
                         only_chars_validator)

# Create your models here.


class CategoryManager(models.Manager):
    def published(self):
        return self.get_queryset().filter(is_published=True).order_by("name")


class CatalogCategory(AbstractModelForCatalog):
    objects = CategoryManager()

    slug = models.CharField(
        unique=True,
        default="",
        validators=[only_chars_validator],
        max_length=200,
        verbose_name="Тэг",
    )
    weight = models.IntegerField(
        default=100, validators=[num_compare_validator], verbose_name="Вес"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class CatalogTag(AbstractModelForCatalog):
    slug = models.CharField(
        unique=True,
        default="",
        validators=[only_chars_validator],
        max_length=200,
        verbose_name="Тэг",
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Тэг"
        verbose_name_plural = "Тэги"


class Photo(models.Model):
    name = models.CharField(max_length=150, default="", verbose_name="Название")
    upload = models.ImageField(upload_to="uploads/")

    @property
    def get_img(self):
        return get_thumbnail(self.upload, "300x300", crop="center", quality=51)

    def image_tmb(self):
        if self.upload:
            return mark_safe(f'<img src="{self.get_img.url}">')
        return "Нет изображения"

    image_tmb.short_description = "Превью"
    image_tmb.allow_tags = True

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Превью"
        verbose_name_plural = "Превью"


class ItemManager(models.Manager):
    def published(self, pk, is_on_main):
        if is_on_main:
            return (
                self.get_queryset()
                .filter(is_published=True, is_on_main=True, category=pk)
                .order_by("name")
            )
        else:
            return (
                self.get_queryset()
                .filter(is_published=True, category=pk)
                .order_by("name")
            )


class CatalogItem(AbstractModelForCatalog):
    objects = ItemManager()

    text = models.TextField(
        default="",
        validators=[in_value_validator("превосходно", "роскошно")],
        verbose_name="Текст",
    )
    category = models.ForeignKey(
        CatalogCategory, on_delete=models.CASCADE, verbose_name="Категория"
    )
    tags = models.ManyToManyField(CatalogTag, verbose_name="Тэги")
    photo = models.OneToOneField(
        Photo, on_delete=models.CASCADE, verbose_name="Превью", null=True, blank=True
    )
    is_on_main = models.BooleanField(default=False, verbose_name="Is_on_main")

    def image_tmb(self):
        if self.photo and self.photo.upload:
            return mark_safe(f'<img src="{self.photo.get_img.url}">')
        return "Нет изображения"

    image_tmb.short_description = "Превью"
    image_tmb.allow_tags = True

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"


class Photos(models.Model):
    item = models.ForeignKey(
        CatalogItem, on_delete=models.CASCADE, related_name="photos"
    )
    photo = models.ImageField(upload_to="photos/")

    def save(self, *args, **kwargs):
        super(Photos, self).save(*args, **kwargs)
        img = Image.open(self.photo.path)
        if img.height > 300 or img.width > 300:
            img.thumbnail((300, 300))
        img.save(self.photo.path, quality=51, optimize=True)

feedback/models.py
from django.db import models


class Feedback(models.Model):
    text = models.TextField(verbose_name="Текст")
    created_at = models.DateTimeField(editable=False, verbose_name="Дата создания")

    class Meta:
        verbose_name = "Обратная связь"
        verbose_name_plural = "Обратная связь"

homepage/models.py
# from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="extrafield"
    )
    birthday = models.DateField("День рождения", blank=True, null=True)

    class Meta:
        verbose_name = "Дополнительное поле"
        verbose_name_plural = "Дополнительные поля"

feedback/forms.py
from django import forms


class FeedbackForm(forms.Form):
    text = forms.CharField(label="Введите текст", help_text="Введите свой отзыв")

users/forms.py
from django import forms
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth.models import User

from .models import Profile


class RegistrationForm(UserCreationForm):
    email = forms.CharField(
        label="Адрес почты", max_length=100, help_text="Введите свою почту"
    )

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]

        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user


class ChangeForm(forms.Form):
    password = forms.CharField(
        label="Пароль", help_text="Введите новый пароль", widget=forms.PasswordInput
    )
    email = forms.CharField(label="Адрес почты", help_text="Введите свою почту")
    birthday = forms.DateField(
        label="Дата рождения", help_text="Введите свою дату рождения"
    )

about/views.py
from django.shortcuts import render

# Create your views here.


def description(request):
    return render(request, "about.html", {"title": "О проекте"})

catalog/views.py
from django.shortcuts import get_object_or_404, render

from .models import CatalogCategory, CatalogItem

# Create your views here.


def item_list(request):
    lst = []
    categories = CatalogCategory.objects.published()
    print(categories)
    for i in categories:
        items = CatalogItem.objects.published(i, False)
        if items:
            lst.append([i.name, items])
    context = {"title": "Список товаров", "dct": lst}
    return render(request, "catalog.html", context)


def item_details(request, num):
    item = get_object_or_404(CatalogItem, id=num, is_published=True)
    context = {"title": "Список товаров", "item": item}
    return render(request, "item_details.html", context)

feedback/views.py
from datetime import datetime

from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render
from pytz import timezone

from .forms import FeedbackForm
from .models import Feedback


def get_feedback(request):
    if request.method == "POST":
        form = FeedbackForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["text"]
            time = timezone("Europe/Moscow").localize(datetime.now())
            Feedback.objects.create(text=text, created_at=time)

            # Здесь сделал условную отправку

            send_mail(
                "Обратная связь",
                text,
                "user@example.com",
                ["reciever@example.com"],
                fail_silently=True,
            )
        return HttpResponseRedirect("/feedback/")
    else:
        form = FeedbackForm()

    return render(request, "feedbackform.html", {"form": form})

homepage/views.py
from django.shortcuts import render

from catalog.models import CatalogCategory, CatalogItem


def home(request):
    lst = []
    categories = CatalogCategory.objects.published()
    for i in categories:
        items = CatalogItem.objects.published(i, True)
        if items:
            lst.append([i.name, items])
    context = {"title": "Главная", "dct": lst}
    return render(request, "homepage.html", context)

users/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework.decorators import permission_classes
from rest_framework.permissions import IsAuthenticated

from .forms import ChangeForm, RegistrationForm
from .models import Profile


def registration(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful.")
            return redirect("/")
    else:
        form = RegistrationForm()
    return render(request, "auth/signup.html", {"form": form})


def users_list(request):
    profiles = User.objects.all()

    context = {"title": "Список пользователей", "users": profiles}
    return render(request, "users.html", context)


def user_details(request, num):
    user = get_object_or_404(User, id=num)
    context = {"title": "подробно о пользователе", "user": user}
    return render(request, "user_details.html", context)


@permission_classes((IsAuthenticated,))
def profile(request):
    if request.method == "POST":
        form = ChangeForm(request.POST)
        if form.is_valid():
            current_user = request.user
            current_user.email = form.cleaned_data["email"]
            current_user.password = form.cleaned_data["password"]
            current_user.save()
            prof = Profile.objects.get(user=current_user)
            prof.save()
            return redirect("/")
    else:
        form = ChangeForm()
    return render(request, "auth/profile.html", {"form": form})

templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>О проекте</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>{{ title }}</title>
  <link rel="icon" type="image/png" href="{% static 'icon.png' %}"/>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="{% static 'js/bootstrap.js' %}"></script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}{% endblock %}
</body>
</html>

templates/catalog.html
{% extends 'base.html' %}
{% block content %}
<h3 class="d-flex justify-content-center">Список товаров</h3>
{% include 'items_table.html' %}
{% endblock %}

templates/feedbackform.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
<form action="/feedback/" method="post">
    {% csrf_token %}

    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}

    {% for field in form %}

        <div class="mb-3">
            <div class="row g-3 align-items-center">
                <div class="col-sm-2">
                    {{ field.label_tag }}
                </div>
                <div class="col-sm-10">
                    {% if field.help_text %}
                        <input class="form-control" name="text" id="id_text" type="text" placeholder="{{ field.help_text }}">
                    {% else %}
                        <input class="form-control" name="text" id="id_text" type="text">
                    {% endif %}
                </div>
            </div>
        </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Отправить</button>

</form>
{% endblock %}
</div>

templates/homepage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="d-flex justify-content-center">Список товаров</h3>
{% include 'items_table.html' %}
{% endblock %}

templates/item_details.html
{% extends 'base.html' %}
{% block content %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ item.name }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ item.category.name }}</h6>
    <p class="card-text">Описание:<br>{{ item.text|safe }}</p>
    <p class="card-text">Тэги:<br>
      {% for i in item.tags.all %}
        {{ i }}
      {% endfor %}
    </p>
  </div>
</div>
{% endblock %}

templates/items_table.html
<table class="table shadow table-striped">
    <thead class="bg-primary text-white">
        <tr>
            <th class="col-3" scope="col">Название</th>
            <th class="col-3" scope="col">Описание</th>
            <th class="col-3" scope="col">Названия тэгов</th>
        </tr>
    </thead>
    <tbody>
        {% for i in dct %}
            <tr class="table-light">
                  <td colspan="3">{{ i.0 }}</td>
            </tr>
            {% for item in i.1 %}
            <tr class="table-light" id="{{ item.id }}">
                <td><a href="../catalog/{{ item.id }}">{{ item.name }}</a></td>

                <td>{{ item.text|safe|truncatewords_html:10 }}</td>
                <td>
                    {% for i in item.tags.all %}
                        {{ i }}
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<div class="collapse navbar-collapse" id="navbarSupportedContent">

  <ul class="navbar-nav mr-auto">
    {% with request.resolver_match.view_name as view_name %}
      {% if view_name == 'homepage:home' %}
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link disabled">Главная</a></li>
        <li class="nav-item"><a href="/catalog" class="nav-link">Список товаров</a></li>
        <li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
        <li class="nav-item"><a href="/feedback" class="nav-link">Обратная связь</a></li>
        <li class="nav-item"><a href="/users" class="nav-link">Список пользователей</a></li>
      {% elif view_name == 'catalog:catalog' %}
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link">Главная</a></li>
        <li class="nav-item"><a href="/catalog" class="nav-link disabled">Список товаров</a></li>
        <li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
        <li class="nav-item"><a href="/feedback" class="nav-link">Обратная связь</a></li>
        <li class="nav-item"><a href="/users" class="nav-link">Список пользователей</a></li>
      {% elif view_name == 'about:about' %}
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link">Главная</a></li>
        <li class="nav-item"><a href="/catalog" class="nav-link">Список товаров</a></li>
        <li class="nav-item"><a href="/about" class="nav-link disabled">О проекте</a></li>
        <li class="nav-item"><a href="/feedback" class="nav-link">Обратная связь</a></li>
        <li class="nav-item"><a href="/users" class="nav-link">Список пользователей</a></li>
      {% elif view_name == 'feedback:feedback' %}
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link">Главная</a></li>
        <li class="nav-item"><a href="/catalog" class="nav-link">Список товаров</a></li>
        <li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
        <li class="nav-item"><a href="/feedback" class="nav-link disabled">Обратная связь</a></li>
        <li class="nav-item"><a href="/users" class="nav-link">Список пользователей</a></li>
      {% else %}
        <li class="nav-item"><a href="{% url 'homepage:home' %}" class="nav-link">Главная</a></li>
        <li class="nav-item"><a href="/catalog" class="nav-link">Список товаров</a></li>
        <li class="nav-item"><a href="/about" class="nav-link">О проекте</a></li>
        <li class="nav-item"><a href="/feedback" class="nav-link">Обратная связь</a></li>
        <li class="nav-item"><a href="/users" class="nav-link disabled">Список пользователей</a></li>
      {% endif %}
    <li class="nav-item"><a href="/registration" class="nav-link">Регистрация</a></li>
    <li class="nav-item"><a href="/profile" class="nav-link">Редактировать профиль</a></li>
    {% endwith %}
  </ul>
</div>
</nav>

templates/user_details.html
{% extends 'base.html' %}
{% block content %}
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{ user.username }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{ user.email}}</h6>
  </div>
</div>
{% endblock %}

templates/users.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h3 class="d-flex justify-content-center">Список товаров</h3>
{% include 'users_list.html' %}
{% endblock %}

templates/users_list.html
<table class="table shadow table-striped">
    <thead class="bg-primary text-white">
        <tr>
            <th class="col-3" scope="col">Имя пользователя</th>
            <th class="col-3" scope="col">Адрес почты</th>
            <th class="col-3" scope="col">Имя</th>
            <th class="col-3" scope="col">Фамилия</th>
        </tr>
    </thead>
    <tbody>
          {% for user in users %}
          <tr class="table-light" id="{{ user.id }}">
              <td><a href="../users/{{ user.id }}">{{ user.username }}</a></td>
              <td>{{ user.email }}</td>
              <td>{{ user.first_name }}</td>
              <td>{{ user.last_name }}</td>
          </tr>
          {% endfor %}
    </tbody>
</table>